return {
	{
		"petertriho/nvim-scrollbar",
		event = "VeryLazy",
		config = function()
			require("scrollbar").setup({
				show = true,
				show_in_active_only = false,
				hide_if_all_visible = false,
				set_highlights = true,
				throttle_ms = 100,
				handle = {
					text = " ",
					blend = 30,
					color = nil,
					color_nr = nil,
					highlight = "CursorColumn",
					hide = false,
				},
				marks = {
					Cursor = {
						text = "█",
						priority = 0,
						gui = nil,
						color = nil,
						cterm = nil,
						color_nr = nil,
						highlight = "Normal",
					},
					Search = {
						text = { "-", "=" },
						priority = 1,
						gui = nil,
						color = nil,
						cterm = nil,
						color_nr = nil,
						highlight = "Search",
					},
					Error = {
						text = { "-", "=" },
						priority = 2,
						gui = nil,
						color = nil,
						cterm = nil,
						color_nr = nil,
						highlight = "DiagnosticVirtualTextError",
					},
					Warn = {
						text = { "-", "=" },
						priority = 3,
						gui = nil,
						color = nil,
						cterm = nil,
						color_nr = nil,
						highlight = "DiagnosticVirtualTextWarn",
					},
					Info = {
						text = { "-", "=" },
						priority = 4,
						gui = nil,
						color = nil,
						cterm = nil,
						color_nr = nil,
						highlight = "DiagnosticVirtualTextInfo",
					},
					Hint = {
						text = { "-", "=" },
						priority = 5,
						gui = nil,
						color = nil,
						cterm = nil,
						color_nr = nil,
						highlight = "DiagnosticVirtualTextHint",
					},
					GitAdd = {
						text = "|",
						priority = 7,
						gui = nil,
						color = nil,
						cterm = nil,
						color_nr = nil,
						highlight = "GitSignsAdd",
					},
					GitChange = {
						text = "|",
						priority = 7,
						gui = nil,
						color = nil,
						cterm = nil,
						color_nr = nil,
						highlight = "GitSignsChange",
					},
					GitDelete = {
						text = "▁",
						priority = 7,
						gui = nil,
						color = nil,
						cterm = nil,
						color_nr = nil,
						highlight = "GitSignsDelete",
					},
				},
				excluded_buftypes = {
					"terminal",
				},
				excluded_filetypes = {
					"cmp_docs",
					"cmp_menu",
					"noice",
					"prompt",
					"TelescopePrompt",
					"alpha",
					"dashboard",
					"neo-tree",
					"NvimTree",
					"nvim-tree",
					"Trouble",
					"trouble",
					"lazy",
					"mason",
					"notify",
					"toggleterm",
					"lazyterm",
				},
				autocmd = {
					render = {
						"BufWinEnter",
						"TabEnter",
						"TermEnter",
						"WinEnter",
						"CmdwinLeave",
						"TextChanged",
						"VimResized",
						"WinScrolled",
					},
					clear = {
						"BufWinLeave",
						"TabLeave",
						"TermLeave",
						"WinLeave",
					},
				},
				handlers = {
					cursor = true,
					diagnostic = true,
					gitsigns = true,
					handle = true,
					search = false,
					ale = false,
				},
			})
		end,
	},
}
