#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

bar=(
  position=top
  height=24
  blur_radius=30
  color=$BAR_COLOR
  display=main
  y_offset=2
  margin=2
)
sketchybar --bar "${bar[@]}"

default=(
  updates=when_shown
  icon.font="$DEFAULT_ICON_FONT"
  icon.color=$WHITE
  icon.padding_left=4
  icon.padding_right=4
  label.font="$DEFAULT_LABEL_FONT"
  label.color=$WHITE
  label.padding_left=4
  label.padding_right=4
  background.height=20
)

sketchybar --default "${default[@]}"
sketchybar --add event aerospace_workspace_change
sketchybar --add event space_windows_change

# -- Left Side Items --
source $ITEM_DIR/apple.sh
source $ITEM_DIR/spaces.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh

sketchybar --update
