k9s:
  liveViewAutoRefresh: true
  screenDumpDir: /tmp/k9s-screen-dumps
  apiServerTimeout: 15s
  ui:
    logoless: true
    crumbsless: true
    splashless: true
    skin: catppuccin-mocha
  skipLatestRevCheck: true
  disablePodCounting: false
  logger:
    tail: 500
    showTime: true
