onboarding = false

[keys]
prefix = "ctrl+a"

[[keys.command]]
key = "prefix+alt+g"
type = "pane"
command = "lazygit"

[theme]
name = "terminal"

auto_switch = false
[theme.custom]
accent = "#313244"
panel_bg = "reset"

[terminal]
default_shell = "zsh"

[ui]
mouse_scroll_lines = 5

[ui.toast]
delivery = "system"

[ui.sound]
enabled = false

[experimental]
pane_history = true
switch_ascii_input_source_in_prefix = true
